#' @title "ah_shiny" - Creates a Shiny dashboard for data analysis
#'
#' @description Creates a Shiny dashboard for data analysis
#'
#' @author Deepankar Datta <deepankardatta@nhs.net>
#'
#' @import dplyr
#' @import purrr
#' @import shiny
#' @import ggplot2
#'
#' @param health_data A data frame containing extracted health data, in a format generated by the ah_import_xml.r function
#'
#' @examples
#' # ah_shiny( health_data )
#'
#' @export

ah_shiny <- function(health_data) {

  # Makes a list of the type factors, aka the health data variables measured
  ah_type_list <- levels(health_data$type)

  require(shiny)
  shinyApp(
    ui = fluidPage(
      titlePanel("Apple Health Analysis Shiny Dashboard"),

      sidebarLayout(
        sidebarPanel(

          #dateRangeInput start

          # A decision was made not to make this a reactice element (yet!)
          # This is a design decision: it seems more useful to have the date
          # ranges set for global data, than re-do the date ranges for each
          # individual health variable when selected

          dateRangeInput( inputId = "dates_to_explore",
                          label = "Dates to explore: ",
                          start = NULL,
                          end = NULL,
                          min = NULL,
                          max = NULL,
                          format = "yyyy-mm-dd",
                          startview = "month",
                          weekstart = 1,
                          language = "en",
                          separator = " to "),

          # END

          #Health data variable selection drop box

          selectInput( inputId = "health_variable",
                       label = "Choose a health variable to display",
                       choices = ah_type_list, # End of choices
                       selected = "HeartRate",
                       multiple = FALSE,
                       selectize = TRUE)

          #END

          # Could also consider putting a file input and export box here

          ),

        mainPanel( # Start of Shiny dashboard output
          textOutput("selected_var"),
          plotOutput("ah_plot")
          )
      )
    ),
    server = function(input, output) {

      # Test as per Shiny examples
      output$selected_var <- renderText({
        paste("You have viewing a plot of ", input$health_variable,
              " from ", input$dates_to_explore[1], " to ", input$dates_to_explore[2])
      })

      # Use the Shiny reactive function to filter to the variable the user wants
      data_to_plot <- reactive({

        health_data %>%
          filter( type == input$health_variable ) %>%
          filter( date >= input$dates_to_explore[1] & date <= input$dates_to_explore[2] )

      })

      # The plot generation output
      output$ah_plot <- renderPlot({
        ah_plot <- ggplot(data_to_plot(), aes(x=date, y=value)) +
          geom_point() +
          theme_grey() +
          labs(x="Date", y=input$health_variable)
        ah_plot
      })
    }
  )
}
